# Generated by Django 2.1 on 2018-09-03 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookbuy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('book_title', models.CharField(max_length=100)),
                ('isbn_no', models.CharField(max_length=20)),
                ('author', models.CharField(blank=True, max_length=100)),
                ('price', models.IntegerField()),
                ('bargain', models.CharField(choices=[('1', 'YES'), ('2', 'NO')], max_length=3)),
                ('description', models.CharField(max_length=2000)),
                ('photo', models.ImageField(blank='True', upload_to='photo')),
            ],
        ),
    ]
