# Generated by Django 2.1 on 2018-09-03 17:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookapp', '0002_bookbuy_owner'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bookbuy',
            new_name='Sell_book',
        ),
    ]
