# Generated by Django 2.1 on 2018-09-30 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0003_auto_20180903_1729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sell_book',
            name='bargain',
        ),
        migrations.AddField(
            model_name='sell_book',
            name='negotiable',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default=1, max_length=3),
            preserve_default=False,
        ),
    ]
