# Generated by Django 2.1 on 2018-10-01 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0004_auto_20180930_0257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sell_book',
            name='photo',
            field=models.FileField(upload_to=''),
        ),
    ]
