# Generated by Django 2.1 on 2018-10-01 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0005_auto_20181001_0206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sell_book',
            name='photo',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
